root: true
env:
  browser: true
  es2021: true
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  extraFileExtensions:
    - '.vue'
plugins:
  - 'vue'
  - '@typescript-eslint'
  - 'prettier'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - '@vue/typescript'
  - 'plugin:vue/strongly-recommended'
  - 'plugin:prettier/recommended'
  - 'prettier'

rules:
  '@typescript-eslint/no-empty-interface':
    - 'error'
  '@typescript-eslint/no-explicit-any':
    - 'error'
  '@typescript-eslint/no-unused-vars':
    - 'error'
  '@typescript-eslint/no-empty-function':
    - 'error'
    - "allow":
      - "constructors"
  "@typescript-eslint/naming-convention":
    - 'error'
    - "selector": "class"
      "format":
        - "PascalCase"
    - "selector": "interface"
      "format":
        - "PascalCase"
      "custom":
        "regex": "^I[A-Z]"
        "match": false
    - "selector": "typeAlias"
      "format":
        - "PascalCase"
      "suffix":
        - "Type"
    - "selector": "typeParameter"
      "format":
        - "UPPER_CASE"
    - "selector": "variable"
      "format":
        - "camelCase"
        - "UPPER_CASE"
    - "selector":
      - "parameter"
      - "function"
      "format":
        - 'camelCase'
      # 「_」 始まりは許す
      "leadingUnderscore": "allow"
      "trailingUnderscore": "allow"

  # typescript-eslint の .prettierrc.json をコピー
  'prettier/prettier':
    - 'error'
    - "arrowParens": "avoid"
      "bracketSpacing": true
      "endOfLine": "lf"
      "printWidth": 100
      "proseWrap": "preserve"
      "quoteProps": "as-needed"
      "semi": true
      "singleQuote": true
      "tabWidth": 2
      "trailingComma": "all"
      "useTabs": false
